import { Injectable } from '@angular/core';
import { Event, SportType } from '../models/event.model';

@Injectable({
  providedIn: 'root'
})
export class MockDataService {
  
  private mockEvents: Event[] = [
    // Badminton Events
    {
      id: '1',
      title: 'Saturday Morning Badminton',
      sport: 'Badminton',
      date: '2025-10-18',
      time: '09:00 AM',
      location: 'Manhattan, NY',
      venue: 'Chelsea Sports Complex',
      price: 25,
      currentParticipants: 6,
      maxParticipants: 8,
      skillLevel: 'Intermediate',
      hostName: 'Alex Chen',
      hostAvatar: '👨',
      description: 'Friendly badminton session for intermediate players. All equipment provided!',
      image: '🏸',
      distance: '1.4 mi',
      bannerImage: 'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=800&h=400&fit=crop'
    },
    {
      id: '2',
      title: 'Evening Badminton Singles',
      sport: 'Badminton',
      date: '2025-10-20',
      time: '06:00 PM',
      location: 'Brooklyn, NY',
      venue: 'Prospect Park Recreation Center',
      price: 30,
      currentParticipants: 7,
      maxParticipants: 8,
      skillLevel: 'Advanced',
      hostName: 'Sarah Johnson',
      hostAvatar: '👩',
      description: 'Competitive singles practice',
      image: '🏸',
      distance: '7.0 mi',
      bannerImage: 'https://images.unsplash.com/photo-1599474924187-334a4ae5bd3c?w=800&h=400&fit=crop'
    },
    {
      id: '3',
      title: 'Beginner Badminton Clinic',
      sport: 'Badminton',
      date: '2025-10-22',
      time: '10:00 AM',
      location: 'Queens, NY',
      venue: 'Flushing Meadows Sports Center',
      price: 20,
      currentParticipants: 4,
      maxParticipants: 12,
      skillLevel: 'Beginner',
      hostName: 'Coach Mike',
      hostAvatar: '👨‍🏫',
      description: 'Learn badminton basics from scratch',
      image: '🏸',
      distance: '4.8 mi'
    },
    
    // Hiking Events
    {
      id: '4',
      title: 'Sunset Hiking at Bear Mountain',
      sport: 'Hiking',
      date: '2025-10-19',
      time: '04:00 PM',
      location: 'Bear Mountain, NY',
      venue: 'Bear Mountain State Park',
      price: 35,
      currentParticipants: 12,
      maxParticipants: 20,
      skillLevel: 'Beginner',
      hostName: 'Sarah Adventure',
      hostAvatar: '👩‍🦰',
      description: 'Join us for a beautiful sunset hike! Perfect for beginners.',
      image: '⛰️',
      distance: '9.8 mi',
      bannerImage: 'https://images.unsplash.com/photo-1551632811-561732d1e306?w=800&h=400&fit=crop'
    },
    {
      id: '5',
      title: 'Weekend Trek to Blue Ridge',
      sport: 'Hiking',
      date: '2025-10-25',
      time: '06:00 AM',
      location: 'Asheville, NC',
      venue: 'Blue Ridge Parkway',
      price: 55,
      currentParticipants: 15,
      maxParticipants: 25,
      skillLevel: 'Intermediate',
      hostName: 'Mountain Warriors',
      hostAvatar: '🧗',
      description: 'Full day hiking adventure',
      image: '⛰️',
      distance: '11.5 mi',
      bannerImage: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&h=400&fit=crop'
    },
    {
      id: '6',
      title: 'Easy Nature Walk',
      sport: 'Hiking',
      date: '2025-10-21',
      time: '07:00 AM',
      location: 'Central Park, NY',
      venue: 'Central Park North Woods',
      price: 0,
      currentParticipants: 8,
      maxParticipants: 30,
      skillLevel: 'Beginner',
      hostName: 'Nature Lovers',
      hostAvatar: '🌳',
      description: 'Relaxed morning nature walk',
      image: '🥾',
      distance: '5.8 mi',
      bannerImage: 'https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?w=800&h=400&fit=crop'
    },

    // Basketball Events
    {
      id: '7',
      title: 'Friday Night Basketball',
      sport: 'Basketball',
      date: '2025-10-17',
      time: '07:00 PM',
      location: 'Bronx, NY',
      venue: 'Rucker Park',
      price: 20,
      currentParticipants: 9,
      maxParticipants: 10,
      skillLevel: 'Intermediate',
      hostName: 'Mike Jordan',
      hostAvatar: '🏀',
      description: 'Casual 5v5 basketball game. Almost full!',
      image: '🏀',
      distance: '5.3 mi',
      bannerImage: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=800&h=400&fit=crop'
    },
    {
      id: '8',
      title: '3v3 Street Basketball',
      sport: 'Basketball',
      date: '2025-10-23',
      time: '05:00 PM',
      location: 'Los Angeles, CA',
      venue: 'Venice Beach Courts',
      price: 15,
      currentParticipants: 5,
      maxParticipants: 6,
      skillLevel: 'Advanced',
      hostName: 'Hoop Dreams',
      hostAvatar: '⛹️',
      description: 'Fast-paced 3v3 tournament',
      image: '🏀',
      distance: '2.6 mi',
      bannerImage: 'https://images.unsplash.com/photo-1574623452334-1e0ac2b3ccb4?w=800&h=400&fit=crop'
    },
    {
      id: '9',
      title: 'Weekend Basketball League',
      sport: 'Basketball',
      date: '2025-10-26',
      time: '09:00 AM',
      location: 'Chicago, IL',
      venue: 'Grant Park Basketball Courts',
      price: 25,
      currentParticipants: 16,
      maxParticipants: 20,
      skillLevel: 'Intermediate',
      hostName: 'Chicago Ballers',
      hostAvatar: '🏀',
      description: 'Organized league matches',
      image: '🏀',
      distance: '8.5 mi'
    },

    // Tennis Events
    {
      id: '10',
      title: 'Tennis Practice',
      sport: 'Tennis',
      date: '2025-10-18',
      time: '10:00 AM',
      location: 'Manhattan, NY',
      venue: 'Central Park Tennis Center',
      price: 50,
      currentParticipants: 3,
      maxParticipants: 4,
      skillLevel: 'Advanced',
      hostName: 'Coach Andre',
      hostAvatar: '🎾',
      description: 'Professional tennis practice session',
      image: '🎾',
      distance: '2.9 mi',
      bannerImage: 'https://images.unsplash.com/photo-1554068865-24cecd4e34b8?w=800&h=400&fit=crop'
    },
    {
      id: '11',
      title: 'Doubles Tennis Match',
      sport: 'Tennis',
      date: '2025-10-24',
      time: '04:00 PM',
      location: 'Miami, FL',
      venue: 'Miami Beach Tennis Club',
      price: 40,
      currentParticipants: 6,
      maxParticipants: 8,
      skillLevel: 'Intermediate',
      hostName: 'Doubles Pro',
      hostAvatar: '🎾',
      description: 'Friendly doubles matches',
      image: '🎾',
      distance: '6.3 mi',
      bannerImage: 'https://images.unsplash.com/photo-1622279457486-62dcc4a431d6?w=800&h=400&fit=crop'
    },
    {
      id: '12',
      title: 'Beginner Tennis Workshop',
      sport: 'Tennis',
      date: '2025-10-27',
      time: '08:00 AM',
      location: 'San Diego, CA',
      venue: 'Balboa Park Tennis Courts',
      price: 65,
      currentParticipants: 8,
      maxParticipants: 15,
      skillLevel: 'Beginner',
      hostName: 'Tennis Academy',
      hostAvatar: '🎾',
      description: 'Learn tennis fundamentals',
      image: '🎾',
      distance: '5.5 mi'
    },

    // Padel Events
    {
      id: '13',
      title: 'Padel Tournament',
      sport: 'Padel',
      date: '2025-10-18',
      time: '02:00 PM',
      location: 'Austin, TX',
      venue: 'Austin Padel Club',
      price: 45,
      currentParticipants: 14,
      maxParticipants: 16,
      skillLevel: 'Advanced',
      hostName: 'David Martinez',
      hostAvatar: '🎾',
      description: 'Competitive padel tournament. Advanced players only!',
      image: '🎾',
      distance: '3.2 mi',
      bannerImage: 'https://images.unsplash.com/photo-1612872087720-bb876e2e67d1?w=800&h=400&fit=crop'
    },
    {
      id: '14',
      title: 'Casual Padel Session',
      sport: 'Padel',
      date: '2025-10-22',
      time: '06:30 PM',
      location: 'Houston, TX',
      venue: 'Memorial Park Padel Courts',
      price: 35,
      currentParticipants: 4,
      maxParticipants: 8,
      skillLevel: 'Intermediate',
      hostName: 'Padel Lovers',
      hostAvatar: '🎾',
      description: 'Relaxed padel for fun',
      image: '🎾',
      distance: '4.0 mi'
    },

    // Volleyball Events
    {
      id: '15',
      title: 'Beach Volleyball Session',
      sport: 'Volleyball',
      date: '2025-10-21',
      time: '05:00 PM',
      location: 'Santa Monica, CA',
      venue: 'Santa Monica Beach',
      price: 25,
      currentParticipants: 4,
      maxParticipants: 12,
      skillLevel: 'Beginner',
      hostName: 'Beach Crew',
      hostAvatar: '🏐',
      description: 'Fun beach volleyball for everyone!',
      image: '🏐',
      distance: '7.7 mi',
      bannerImage: 'https://images.unsplash.com/photo-1612872087720-bb876e2e67d1?w=800&h=400&fit=crop'
    },
    {
      id: '16',
      title: 'Indoor Volleyball League',
      sport: 'Volleyball',
      date: '2025-10-19',
      time: '07:00 PM',
      location: 'Seattle, WA',
      venue: 'Seattle Sports Complex',
      price: 20,
      currentParticipants: 11,
      maxParticipants: 12,
      skillLevel: 'Intermediate',
      hostName: 'Spike Masters',
      hostAvatar: '🏐',
      description: 'Competitive indoor volleyball',
      image: '🏐',
      distance: '6.1 mi',
      bannerImage: 'https://images.unsplash.com/photo-1612872087720-bb876e2e67d1?w=800&h=400&fit=crop'
    },
    {
      id: '17',
      title: 'Mixed Volleyball Tournament',
      sport: 'Volleyball',
      date: '2025-10-28',
      time: '10:00 AM',
      location: 'Portland, OR',
      venue: 'Portland Recreation Center',
      price: 30,
      currentParticipants: 18,
      maxParticipants: 24,
      skillLevel: 'Advanced',
      hostName: 'VB Champions',
      hostAvatar: '🏐',
      description: 'High-level mixed tournament',
      image: '🏐',
      distance: '8.9 mi'
    },

    // Running Events
    {
      id: '18',
      title: 'Morning Run Group',
      sport: 'Running',
      date: '2025-10-19',
      time: '05:30 AM',
      location: 'Boston, MA',
      venue: 'Boston Common',
      price: 0,
      currentParticipants: 25,
      maxParticipants: 50,
      skillLevel: 'Beginner',
      hostName: 'Boston Runners',
      hostAvatar: '🏃',
      description: 'Weekly morning run, 3-mile route. Free!',
      image: '🏃',
      distance: '3.9 mi',
      bannerImage: 'https://images.unsplash.com/photo-1483721310020-03333e577078?w=800&h=400&fit=crop'
    },
    {
      id: '19',
      title: '10K Charity Run',
      sport: 'Running',
      date: '2025-10-26',
      time: '06:00 AM',
      location: 'San Francisco, CA',
      venue: 'Golden Gate Park',
      price: 45,
      currentParticipants: 45,
      maxParticipants: 100,
      skillLevel: 'Intermediate',
      hostName: 'Run for Good',
      hostAvatar: '🏃',
      description: 'Fundraising 10K run',
      image: '🏃',
      distance: '2.2 mi',
      bannerImage: 'https://images.unsplash.com/photo-1452626038306-9aae5e071dd3?w=800&h=400&fit=crop'
    },
    {
      id: '20',
      title: 'Trail Running Adventure',
      sport: 'Running',
      date: '2025-10-23',
      time: '07:00 AM',
      location: 'Denver, CO',
      venue: 'Red Rocks Trail',
      price: 40,
      currentParticipants: 12,
      maxParticipants: 30,
      skillLevel: 'Advanced',
      hostName: 'Trail Blazers',
      hostAvatar: '🏃‍♂️',
      description: '9-mile trail running',
      image: '🏃',
      distance: '13.8 mi',
      bannerImage: 'https://images.unsplash.com/photo-1513593771513-7b58b6c4af38?w=800&h=400&fit=crop'
    },
    {
      id: '21',
      title: 'Evening Jog & Social',
      sport: 'Running',
      date: '2025-10-20',
      time: '06:00 PM',
      location: 'Brooklyn, NY',
      venue: 'Brooklyn Bridge Park',
      price: 0,
      currentParticipants: 15,
      maxParticipants: 40,
      skillLevel: 'Beginner',
      hostName: 'Social Runners',
      hostAvatar: '🏃‍♀️',
      description: 'Easy jog followed by coffee',
      image: '🏃',
      distance: '4.7 mi'
    },

    // Yoga Events
    {
      id: '22',
      title: 'Morning Yoga in the Park',
      sport: 'Yoga',
      date: '2025-10-20',
      time: '06:00 AM',
      location: 'Central Park, NY',
      venue: 'Sheep Meadow',
      price: 0,
      currentParticipants: 8,
      maxParticipants: 15,
      skillLevel: 'Beginner',
      hostName: 'Rina Wellness',
      hostAvatar: '🧘',
      description: 'Free outdoor yoga session. Bring your own mat!',
      image: '🧘',
      distance: '0.8 mi',
      bannerImage: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&h=400&fit=crop'
    },
    {
      id: '23',
      title: 'Power Yoga Class',
      sport: 'Yoga',
      date: '2025-10-22',
      time: '07:00 PM',
      location: 'Los Angeles, CA',
      venue: 'West Hollywood Yoga Studio',
      price: 50,
      currentParticipants: 10,
      maxParticipants: 20,
      skillLevel: 'Intermediate',
      hostName: 'Yoga Master Nina',
      hostAvatar: '🧘‍♀️',
      description: 'Intense power yoga workout',
      image: '🧘',
      distance: '3.0 mi',
      bannerImage: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800&h=400&fit=crop'
    },
    {
      id: '24',
      title: 'Sunset Beach Yoga',
      sport: 'Yoga',
      date: '2025-10-24',
      time: '05:00 PM',
      location: 'Malibu, CA',
      venue: 'Zuma Beach',
      price: 35,
      currentParticipants: 12,
      maxParticipants: 25,
      skillLevel: 'Beginner',
      hostName: 'Beach Zen',
      hostAvatar: '🧘',
      description: 'Relaxing yoga with ocean view',
      image: '🧘',
      distance: '7.4 mi',
      bannerImage: 'https://images.unsplash.com/photo-1588286840104-8957b019727f?w=800&h=400&fit=crop'
    },
    {
      id: '25',
      title: 'Hot Yoga Session',
      sport: 'Yoga',
      date: '2025-10-25',
      time: '09:00 AM',
      location: 'Manhattan, NY',
      venue: 'SoHo Hot Yoga',
      price: 65,
      currentParticipants: 14,
      maxParticipants: 15,
      skillLevel: 'Advanced',
      hostName: 'Hot Yoga Pro',
      hostAvatar: '🧘‍♂️',
      description: '90-minute hot yoga class',
      image: '🧘',
      distance: '3.3 mi'
    },

    // Soccer/Football Events
    {
      id: '26',
      title: 'Friday Night Soccer',
      sport: 'Running',
      date: '2025-10-17',
      time: '08:00 PM',
      location: 'Queens, NY',
      venue: 'Astoria Park Field',
      price: 25,
      currentParticipants: 9,
      maxParticipants: 10,
      skillLevel: 'Intermediate',
      hostName: 'Soccer Heroes',
      hostAvatar: '⚽',
      description: '5v5 indoor soccer match',
      image: '⚽',
      distance: '3.6 mi',
      bannerImage: 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=800&h=400&fit=crop'
    },
    {
      id: '27',
      title: 'Sunday Football League',
      sport: 'Running',
      date: '2025-10-27',
      time: '08:00 AM',
      location: 'San Jose, CA',
      venue: 'Almaden Lake Park',
      price: 20,
      currentParticipants: 18,
      maxParticipants: 22,
      skillLevel: 'Beginner',
      hostName: 'Weekend Warriors',
      hostAvatar: '⚽',
      description: 'Casual 11v11 football',
      image: '⚽',
      distance: '5.2 mi',
      bannerImage: 'https://images.unsplash.com/photo-1553778263-73a83bab9b0c?w=800&h=400&fit=crop'
    },
    {
      id: '28',
      title: 'Kids Soccer Training',
      sport: 'Running',
      date: '2025-10-21',
      time: '02:00 PM',
      location: 'Austin, TX',
      venue: 'Zilker Park',
      price: 35,
      currentParticipants: 12,
      maxParticipants: 20,
      skillLevel: 'Beginner',
      hostName: 'Coach Fernando',
      hostAvatar: '⚽',
      description: 'Training for kids 8-12 years',
      image: '⚽',
      distance: '8.0 mi'
    },

    // Cycling Events
    {
      id: '29',
      title: 'Weekend Cycling Tour',
      sport: 'Running',
      date: '2025-10-26',
      time: '06:00 AM',
      location: 'Napa Valley, CA',
      venue: 'Napa Valley Bike Path',
      price: 25,
      currentParticipants: 22,
      maxParticipants: 40,
      skillLevel: 'Beginner',
      hostName: 'Bike Squad',
      hostAvatar: '🚴',
      description: '18-mile leisure cycling',
      image: '🚴',
      distance: '10.2 mi',
      bannerImage: 'https://images.unsplash.com/photo-1541625602330-2277a4c46182?w=800&h=400&fit=crop'
    },
    {
      id: '30',
      title: 'Mountain Bike Challenge',
      sport: 'Running',
      date: '2025-10-25',
      time: '07:00 AM',
      location: 'Moab, UT',
      venue: 'Slickrock Trail',
      price: 55,
      currentParticipants: 15,
      maxParticipants: 25,
      skillLevel: 'Advanced',
      hostName: 'MTB Champions',
      hostAvatar: '🚵',
      description: 'Challenging mountain bike trail',
      image: '🚴',
      distance: '13.4 mi',
      bannerImage: 'https://images.unsplash.com/photo-1544191696-102dbdaeeaa0?w=800&h=400&fit=crop'
    },
    {
      id: '31',
      title: 'City Night Ride',
      sport: 'Running',
      date: '2025-10-18',
      time: '08:00 PM',
      location: 'Chicago, IL',
      venue: 'Lake Shore Drive',
      price: 0,
      currentParticipants: 35,
      maxParticipants: 60,
      skillLevel: 'Beginner',
      hostName: 'Night Riders',
      hostAvatar: '🚴‍♂️',
      description: 'Free night cycling tour',
      image: '🚴',
      distance: '2.6 mi',
      bannerImage: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=400&fit=crop'
    },

    // Swimming Events
    {
      id: '32',
      title: 'Early Morning Swim',
      sport: 'Running',
      date: '2025-10-20',
      time: '05:30 AM',
      location: 'Manhattan, NY',
      venue: 'Chelsea Piers Aquatic Center',
      price: 20,
      currentParticipants: 8,
      maxParticipants: 20,
      skillLevel: 'Intermediate',
      hostName: 'Swim Team',
      hostAvatar: '🏊',
      description: 'Open lane swimming session',
      image: '🏊',
      distance: '3.1 mi',
      bannerImage: 'https://images.unsplash.com/photo-1519315901367-f34ff9154487?w=800&h=400&fit=crop'
    },
    {
      id: '33',
      title: 'Swimming Lesson for Adults',
      sport: 'Running',
      date: '2025-10-23',
      time: '06:00 PM',
      location: 'Miami, FL',
      venue: 'Miami Beach Aquatic Center',
      price: 45,
      currentParticipants: 6,
      maxParticipants: 10,
      skillLevel: 'Beginner',
      hostName: 'Coach Michael',
      hostAvatar: '🏊‍♂️',
      description: 'Learn to swim basics',
      image: '🏊',
      distance: '5.7 mi',
      bannerImage: 'https://images.unsplash.com/photo-1530549387789-4c1017266635?w=800&h=400&fit=crop'
    },
    {
      id: '34',
      title: 'Triathlon Training Swim',
      sport: 'Running',
      date: '2025-10-24',
      time: '06:00 AM',
      location: 'San Diego, CA',
      venue: 'Mission Bay Aquatic Center',
      price: 30,
      currentParticipants: 12,
      maxParticipants: 15,
      skillLevel: 'Advanced',
      hostName: 'Tri-Athletes',
      hostAvatar: '🏊',
      description: 'Intensive swim training',
      image: '🏊',
      distance: '6.7 mi'
    },

    // Boxing/Martial Arts
    {
      id: '35',
      title: 'Boxing Fitness Class',
      sport: 'Running',
      date: '2025-10-22',
      time: '06:30 PM',
      location: 'Brooklyn, NY',
      venue: 'Gleason\'s Gym',
      price: 40,
      currentParticipants: 11,
      maxParticipants: 15,
      skillLevel: 'Intermediate',
      hostName: 'Coach Rocky',
      hostAvatar: '🥊',
      description: 'High intensity boxing workout',
      image: '🥊',
      distance: '3.8 mi',
      bannerImage: 'https://images.unsplash.com/photo-1549719386-74dfcbf7dbed?w=800&h=400&fit=crop'
    },
    {
      id: '36',
      title: 'Muay Thai Fundamentals',
      sport: 'Running',
      date: '2025-10-19',
      time: '07:00 PM',
      location: 'Los Angeles, CA',
      venue: 'Hollywood Muay Thai',
      price: 50,
      currentParticipants: 8,
      maxParticipants: 12,
      skillLevel: 'Beginner',
      hostName: 'Master Somchai',
      hostAvatar: '🥋',
      description: 'Introduction to Muay Thai',
      image: '🥊',
      distance: '3.4 mi',
      bannerImage: 'https://images.unsplash.com/photo-1555597673-b21d5c935865?w=800&h=400&fit=crop'
    },
    {
      id: '37',
      title: 'Kickboxing Sparring',
      sport: 'Running',
      date: '2025-10-27',
      time: '05:00 PM',
      location: 'Las Vegas, NV',
      venue: 'Champions Gym',
      price: 35,
      currentParticipants: 9,
      maxParticipants: 10,
      skillLevel: 'Advanced',
      hostName: 'Fight Master',
      hostAvatar: '🥊',
      description: 'Advanced sparring session',
      image: '🥊',
      distance: '9.5 mi'
    },

    // Additional Badminton
    {
      id: '38',
      title: 'Lunch Break Badminton',
      sport: 'Badminton',
      date: '2025-10-21',
      time: '12:00 PM',
      location: 'San Francisco, CA',
      venue: 'Presidio Sports Center',
      price: 30,
      currentParticipants: 6,
      maxParticipants: 8,
      skillLevel: 'Intermediate',
      hostName: 'Office Warriors',
      hostAvatar: '💼',
      description: 'Quick badminton during lunch',
      image: '🏸',
      distance: '2.4 mi',
      bannerImage: 'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=800&h=400&fit=crop'
    },
    {
      id: '39',
      title: 'Mixed Doubles Tournament',
      sport: 'Badminton',
      date: '2025-10-28',
      time: '02:00 PM',
      location: 'Seattle, WA',
      venue: 'Seattle Badminton Club',
      price: 40,
      currentParticipants: 14,
      maxParticipants: 16,
      skillLevel: 'Advanced',
      hostName: 'Tournament Organizer',
      hostAvatar: '🏆',
      description: 'Competitive mixed doubles',
      image: '🏸',
      distance: '7.7 mi'
    },

    // More Basketball
    {
      id: '40',
      title: 'Youth Basketball Camp',
      sport: 'Basketball',
      date: '2025-10-26',
      time: '09:00 AM',
      location: 'Philadelphia, PA',
      venue: 'Temple University Recreation Center',
      price: 65,
      currentParticipants: 24,
      maxParticipants: 30,
      skillLevel: 'Beginner',
      hostName: 'Basketball Academy',
      hostAvatar: '🏫',
      description: 'Training camp for youth 10-16',
      image: '🏀',
      distance: '3.2 mi',
      bannerImage: 'https://images.unsplash.com/photo-1608245449230-4ac19066d2d0?w=800&h=400&fit=crop'
    },
    {
      id: '41',
      title: 'Women\'s Basketball League',
      sport: 'Basketball',
      date: '2025-10-24',
      time: '07:00 PM',
      location: 'Atlanta, GA',
      venue: 'Piedmont Park Courts',
      price: 20,
      currentParticipants: 8,
      maxParticipants: 10,
      skillLevel: 'Intermediate',
      hostName: 'Lady Ballers',
      hostAvatar: '👩‍🦰',
      description: 'Women\'s basketball matches',
      image: '🏀',
      distance: '8.2 mi',
      bannerImage: 'https://images.unsplash.com/photo-1515523110800-9415d13b84a8?w=800&h=400&fit=crop'
    },

    // Table Tennis
    {
      id: '42',
      title: 'Table Tennis Tournament',
      sport: 'Tennis',
      date: '2025-10-23',
      time: '06:00 PM',
      location: 'San Jose, CA',
      venue: 'San Jose Table Tennis Club',
      price: 20,
      currentParticipants: 15,
      maxParticipants: 20,
      skillLevel: 'Intermediate',
      hostName: 'Ping Pong Masters',
      hostAvatar: '🏓',
      description: 'Singles table tennis tournament',
      image: '🏓',
      distance: '7.2 mi'
    },
    {
      id: '43',
      title: 'Beginner Table Tennis Class',
      sport: 'Tennis',
      date: '2025-10-21',
      time: '10:00 AM',
      location: 'Queens, NY',
      venue: 'Flushing Table Tennis Center',
      price: 25,
      currentParticipants: 7,
      maxParticipants: 12,
      skillLevel: 'Beginner',
      hostName: 'Coach Lee',
      hostAvatar: '🏓',
      description: 'Learn table tennis basics',
      image: '🏓',
      distance: '5.2 mi'
    },

    // Golf
    {
      id: '44',
      title: 'Weekend Golf Round',
      sport: 'Running',
      date: '2025-10-26',
      time: '07:00 AM',
      location: 'Scottsdale, AZ',
      venue: 'TPC Scottsdale',
      price: 150,
      currentParticipants: 3,
      maxParticipants: 4,
      skillLevel: 'Intermediate',
      hostName: 'Golf Buddies',
      hostAvatar: '⛳',
      description: '18 holes golf round',
      image: '⛳',
      distance: '10.5 mi'
    },
    {
      id: '45',
      title: 'Golf Clinic for Beginners',
      sport: 'Running',
      date: '2025-10-24',
      time: '08:00 AM',
      location: 'Orlando, FL',
      venue: 'Bay Hill Golf Academy',
      price: 85,
      currentParticipants: 8,
      maxParticipants: 15,
      skillLevel: 'Beginner',
      hostName: 'Pro Golfer',
      hostAvatar: '⛳',
      description: 'Introduction to golf',
      image: '⛳',
      distance: '2.8 mi'
    },

    // Rock Climbing
    {
      id: '46',
      title: 'Indoor Rock Climbing',
      sport: 'Hiking',
      date: '2025-10-22',
      time: '06:00 PM',
      location: 'Brooklyn, NY',
      venue: 'Brooklyn Boulders',
      price: 40,
      currentParticipants: 6,
      maxParticipants: 12,
      skillLevel: 'Beginner',
      hostName: 'Climb Masters',
      hostAvatar: '🧗',
      description: 'Beginner-friendly climbing',
      image: '🧗',
      distance: '4.5 mi',
      bannerImage: 'https://images.unsplash.com/photo-1522163182402-834f871fd851?w=800&h=400&fit=crop'
    },
    {
      id: '47',
      title: 'Advanced Bouldering Session',
      sport: 'Hiking',
      date: '2025-10-25',
      time: '07:00 PM',
      location: 'Boulder, CO',
      venue: 'Movement Climbing Gym',
      price: 45,
      currentParticipants: 9,
      maxParticipants: 10,
      skillLevel: 'Advanced',
      hostName: 'Boulder Bros',
      hostAvatar: '🧗‍♂️',
      description: 'Challenging boulder problems',
      image: '🧗',
      distance: '4.3 mi',
      bannerImage: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=400&fit=crop'
    },

    // More Yoga
    {
      id: '48',
      title: 'Aerial Yoga Class',
      sport: 'Yoga',
      date: '2025-10-27',
      time: '10:00 AM',
      location: 'Miami, FL',
      venue: 'South Beach Aerial Studio',
      price: 75,
      currentParticipants: 7,
      maxParticipants: 10,
      skillLevel: 'Intermediate',
      hostName: 'Aerial Instructor',
      hostAvatar: '🎪',
      description: 'Yoga with hammocks',
      image: '🧘',
      distance: '3.6 mi',
      bannerImage: 'https://images.unsplash.com/photo-1545389336-cf090694435e?w=800&h=400&fit=crop'
    },
    {
      id: '49',
      title: 'Meditation & Yoga Retreat',
      sport: 'Yoga',
      date: '2025-10-28',
      time: '08:00 AM',
      location: 'Sedona, AZ',
      venue: 'Red Rock Yoga Retreat',
      price: 120,
      currentParticipants: 12,
      maxParticipants: 20,
      skillLevel: 'Beginner',
      hostName: 'Zen Master',
      hostAvatar: '🧘‍♂️',
      description: 'Full day yoga and meditation',
      image: '🧘',
      distance: '12.0 mi'
    },

    // Dance Fitness
    {
      id: '50',
      title: 'Zumba Dance Party',
      sport: 'Running',
      date: '2025-10-23',
      time: '07:00 PM',
      location: 'Miami, FL',
      venue: 'Wynwood Dance Studio',
      price: 25,
      currentParticipants: 18,
      maxParticipants: 25,
      skillLevel: 'Beginner',
      hostName: 'Dance Instructor Maria',
      hostAvatar: '💃',
      description: 'High energy dance workout',
      image: '💃',
      distance: '4.9 mi',
      bannerImage: 'https://images.unsplash.com/photo-1504609813442-a8924e83f76e?w=800&h=400&fit=crop'
    },
    {
      id: '51',
      title: 'Hip Hop Dance Class',
      sport: 'Running',
      date: '2025-10-24',
      time: '08:00 PM',
      location: 'Los Angeles, CA',
      venue: 'Hollywood Dance Studio',
      price: 35,
      currentParticipants: 14,
      maxParticipants: 20,
      skillLevel: 'Intermediate',
      hostName: 'B-Boy Danny',
      hostAvatar: '🕺',
      description: 'Learn hip hop choreography',
      image: '💃',
      distance: '3.2 mi',
      bannerImage: 'https://images.unsplash.com/photo-1547153760-18fc86324498?w=800&h=400&fit=crop'
    },

    // CrossFit / HIIT
    {
      id: '52',
      title: 'CrossFit Bootcamp',
      sport: 'Running',
      date: '2025-10-20',
      time: '06:00 AM',
      location: 'Austin, TX',
      venue: 'CrossFit South Austin',
      price: 45,
      currentParticipants: 15,
      maxParticipants: 20,
      skillLevel: 'Advanced',
      hostName: 'Coach Alex',
      hostAvatar: '💪',
      description: 'Intense CrossFit WOD',
      image: '💪',
      distance: '3.9 mi',
      bannerImage: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&h=400&fit=crop'
    },
    {
      id: '53',
      title: 'HIIT Training Session',
      sport: 'Running',
      date: '2025-10-22',
      time: '06:30 PM',
      location: 'Boston, MA',
      venue: 'Back Bay Fitness',
      price: 35,
      currentParticipants: 12,
      maxParticipants: 18,
      skillLevel: 'Intermediate',
      hostName: 'Trainer Sarah',
      hostAvatar: '🏋️',
      description: '45-min high intensity workout',
      image: '💪',
      distance: '7.4 mi',
      bannerImage: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=800&h=400&fit=crop'
    }
  ];

  private sportTypes: SportType[] = [
    { name: 'All', icon: '🎯' },
    { name: 'Badminton', icon: '🏸' },
    { name: 'Hiking', icon: '🥾' },
    { name: 'Padel', icon: '🎾' },
    { name: 'Basketball', icon: '🏀' },
    { name: 'Volleyball', icon: '🏐' },
    { name: 'Tennis', icon: '🎾' },
    { name: 'Running', icon: '🏃' },
    { name: 'Yoga', icon: '🧘' }
  ];

  getEvents(): Event[] {
    return this.mockEvents;
  }

  getSportTypes(): SportType[] {
    return this.sportTypes;
  }

  getEventById(id: string): Event | undefined {
    return this.mockEvents.find(event => event.id === id);
  }
}
