import { Injectable } from '@angular/core';
import { Event, SportType } from '../models/event.model';

@Injectable({
  providedIn: 'root'
})
export class MockDataService {
  
  private mockEvents: Event[] = [
    // Badminton Events
    {
      id: '1',
      title: 'Saturday Morning Badminton',
      sport: 'Badminton',
      date: '2025-10-18',
      time: '09:00 AM',
      location: 'Jakarta Selatan',
      venue: 'GOR Menteng Badminton Court',
      price: 50000,
      currentParticipants: 6,
      maxParticipants: 8,
      skillLevel: 'Intermediate',
      hostName: 'Ahmad Rizki',
      hostAvatar: '👨',
      description: 'Friendly badminton session for intermediate players. All equipment provided!',
      image: '🏸',
      distance: '2.3 km'
    },
    {
      id: '2',
      title: 'Evening Badminton Singles',
      sport: 'Badminton',
      date: '2025-10-20',
      time: '06:00 PM',
      location: 'Tangerang',
      venue: 'BSD Badminton Arena',
      price: 75000,
      currentParticipants: 7,
      maxParticipants: 8,
      skillLevel: 'Advanced',
      hostName: 'Susi Handayani',
      hostAvatar: '👩',
      description: 'Competitive singles practice',
      image: '🏸',
      distance: '11.2 km'
    },
    {
      id: '3',
      title: 'Beginner Badminton Clinic',
      sport: 'Badminton',
      date: '2025-10-22',
      time: '10:00 AM',
      location: 'Jakarta Barat',
      venue: 'Taman Anggrek Sports Center',
      price: 35000,
      currentParticipants: 4,
      maxParticipants: 12,
      skillLevel: 'Beginner',
      hostName: 'Coach Budi',
      hostAvatar: '👨‍🏫',
      description: 'Learn badminton basics from scratch',
      image: '🏸',
      distance: '7.8 km'
    },
    
    // Hiking Events
    {
      id: '4',
      title: 'Sunset Hiking at Gunung Gede',
      sport: 'Hiking',
      date: '2025-10-19',
      time: '04:00 PM',
      location: 'Bogor',
      venue: 'Gunung Gede Trailhead',
      price: 75000,
      currentParticipants: 12,
      maxParticipants: 20,
      skillLevel: 'Beginner',
      hostName: 'Sarah Adventure',
      hostAvatar: '👩‍🦰',
      description: 'Join us for a beautiful sunset hike! Perfect for beginners.',
      image: '⛰️',
      distance: '15.8 km'
    },
    {
      id: '5',
      title: 'Weekend Trek to Gunung Salak',
      sport: 'Hiking',
      date: '2025-10-25',
      time: '06:00 AM',
      location: 'Bogor',
      venue: 'Gunung Salak Base',
      price: 125000,
      currentParticipants: 15,
      maxParticipants: 25,
      skillLevel: 'Intermediate',
      hostName: 'Mountain Warriors',
      hostAvatar: '🧗',
      description: 'Full day hiking adventure',
      image: '⛰️',
      distance: '18.5 km'
    },
    {
      id: '6',
      title: 'Easy Nature Walk',
      sport: 'Hiking',
      date: '2025-10-21',
      time: '07:00 AM',
      location: 'Depok',
      venue: 'Situ Gede',
      price: 0,
      currentParticipants: 8,
      maxParticipants: 30,
      skillLevel: 'Beginner',
      hostName: 'Nature Lovers',
      hostAvatar: '🌳',
      description: 'Relaxed morning nature walk',
      image: '🥾',
      distance: '9.3 km'
    },

    // Basketball Events
    {
      id: '7',
      title: 'Friday Night Basketball',
      sport: 'Basketball',
      date: '2025-10-17',
      time: '07:00 PM',
      location: 'Jakarta Timur',
      venue: 'Lapangan Basket Rawamangun',
      price: 40000,
      currentParticipants: 9,
      maxParticipants: 10,
      skillLevel: 'Intermediate',
      hostName: 'Michael Jordan Jr',
      hostAvatar: '🏀',
      description: 'Casual 5v5 basketball game. Almost full!',
      image: '🏀',
      distance: '8.5 km'
    },
    {
      id: '8',
      title: '3v3 Street Basketball',
      sport: 'Basketball',
      date: '2025-10-23',
      time: '05:00 PM',
      location: 'Jakarta Selatan',
      venue: 'Senayan Street Court',
      price: 25000,
      currentParticipants: 5,
      maxParticipants: 6,
      skillLevel: 'Advanced',
      hostName: 'Hoop Dreams',
      hostAvatar: '⛹️',
      description: 'Fast-paced 3v3 tournament',
      image: '🏀',
      distance: '4.2 km'
    },
    {
      id: '9',
      title: 'Weekend Basketball League',
      sport: 'Basketball',
      date: '2025-10-26',
      time: '09:00 AM',
      location: 'Bekasi',
      venue: 'Grand Metropolitan Mall Court',
      price: 50000,
      currentParticipants: 16,
      maxParticipants: 20,
      skillLevel: 'Intermediate',
      hostName: 'Bekasi Ballers',
      hostAvatar: '🏀',
      description: 'Organized league matches',
      image: '🏀',
      distance: '13.7 km'
    },

    // Tennis Events
    {
      id: '10',
      title: 'Tennis Practice',
      sport: 'Tennis',
      date: '2025-10-18',
      time: '10:00 AM',
      location: 'Jakarta Selatan',
      venue: 'Tennis Indoor Senayan',
      price: 120000,
      currentParticipants: 3,
      maxParticipants: 4,
      skillLevel: 'Advanced',
      hostName: 'Coach Andre',
      hostAvatar: '🎾',
      description: 'Professional tennis practice session',
      image: '🎾',
      distance: '4.7 km'
    },
    {
      id: '11',
      title: 'Doubles Tennis Match',
      sport: 'Tennis',
      date: '2025-10-24',
      time: '04:00 PM',
      location: 'Jakarta Utara',
      venue: 'Kelapa Gading Tennis Club',
      price: 90000,
      currentParticipants: 6,
      maxParticipants: 8,
      skillLevel: 'Intermediate',
      hostName: 'Doubles Pro',
      hostAvatar: '🎾',
      description: 'Friendly doubles matches',
      image: '🎾',
      distance: '10.1 km'
    },
    {
      id: '12',
      title: 'Beginner Tennis Workshop',
      sport: 'Tennis',
      date: '2025-10-27',
      time: '08:00 AM',
      location: 'Jakarta Barat',
      venue: 'Puri Indah Tennis Academy',
      price: 150000,
      currentParticipants: 8,
      maxParticipants: 15,
      skillLevel: 'Beginner',
      hostName: 'Tennis Academy',
      hostAvatar: '🎾',
      description: 'Learn tennis fundamentals',
      image: '🎾',
      distance: '8.9 km'
    },

    // Padel Events
    {
      id: '13',
      title: 'Padel Tournament',
      sport: 'Padel',
      date: '2025-10-18',
      time: '02:00 PM',
      location: 'Jakarta Pusat',
      venue: 'Senayan Padel Club',
      price: 100000,
      currentParticipants: 14,
      maxParticipants: 16,
      skillLevel: 'Advanced',
      hostName: 'David Martinez',
      hostAvatar: '🎾',
      description: 'Competitive padel tournament. Advanced players only!',
      image: '🎾',
      distance: '5.1 km'
    },
    {
      id: '14',
      title: 'Casual Padel Session',
      sport: 'Padel',
      date: '2025-10-22',
      time: '06:30 PM',
      location: 'Jakarta Selatan',
      venue: 'Pondok Indah Padel Court',
      price: 80000,
      currentParticipants: 4,
      maxParticipants: 8,
      skillLevel: 'Intermediate',
      hostName: 'Padel Lovers',
      hostAvatar: '🎾',
      description: 'Relaxed padel for fun',
      image: '🎾',
      distance: '6.4 km'
    },

    // Volleyball Events
    {
      id: '15',
      title: 'Beach Volleyball Session',
      sport: 'Volleyball',
      date: '2025-10-21',
      time: '05:00 PM',
      location: 'Ancol',
      venue: 'Ancol Beach',
      price: 60000,
      currentParticipants: 4,
      maxParticipants: 12,
      skillLevel: 'Beginner',
      hostName: 'Beach Crew',
      hostAvatar: '🏐',
      description: 'Fun beach volleyball for everyone!',
      image: '🏐',
      distance: '12.3 km'
    },
    {
      id: '16',
      title: 'Indoor Volleyball League',
      sport: 'Volleyball',
      date: '2025-10-19',
      time: '07:00 PM',
      location: 'Jakarta Timur',
      venue: 'Klapa Village Sports Hall',
      price: 45000,
      currentParticipants: 11,
      maxParticipants: 12,
      skillLevel: 'Intermediate',
      hostName: 'Spike Masters',
      hostAvatar: '🏐',
      description: 'Competitive indoor volleyball',
      image: '🏐',
      distance: '9.8 km'
    },
    {
      id: '17',
      title: 'Mixed Volleyball Tournament',
      sport: 'Volleyball',
      date: '2025-10-28',
      time: '10:00 AM',
      location: 'Tangerang',
      venue: 'Alam Sutera Sports Complex',
      price: 70000,
      currentParticipants: 18,
      maxParticipants: 24,
      skillLevel: 'Advanced',
      hostName: 'VB Champions',
      hostAvatar: '🏐',
      description: 'High-level mixed tournament',
      image: '🏐',
      distance: '14.2 km'
    },

    // Running Events
    {
      id: '18',
      title: 'Morning Run Group',
      sport: 'Running',
      date: '2025-10-19',
      time: '05:30 AM',
      location: 'Jakarta Pusat',
      venue: 'Gelora Bung Karno',
      price: 0,
      currentParticipants: 25,
      maxParticipants: 50,
      skillLevel: 'Beginner',
      hostName: 'Jakarta Runners',
      hostAvatar: '🏃',
      description: 'Weekly morning run, 5km route. Free!',
      image: '🏃',
      distance: '6.2 km'
    },
    {
      id: '19',
      title: '10K Charity Run',
      sport: 'Running',
      date: '2025-10-26',
      time: '06:00 AM',
      location: 'Jakarta Selatan',
      venue: 'Sudirman Street Start Point',
      price: 100000,
      currentParticipants: 45,
      maxParticipants: 100,
      skillLevel: 'Intermediate',
      hostName: 'Run for Good',
      hostAvatar: '🏃',
      description: 'Fundraising 10K run',
      image: '🏃',
      distance: '3.5 km'
    },
    {
      id: '20',
      title: 'Trail Running Adventure',
      sport: 'Running',
      date: '2025-10-23',
      time: '07:00 AM',
      location: 'Sentul',
      venue: 'Sentul Highlands',
      price: 85000,
      currentParticipants: 12,
      maxParticipants: 30,
      skillLevel: 'Advanced',
      hostName: 'Trail Blazers',
      hostAvatar: '🏃‍♂️',
      description: '15km trail running',
      image: '🏃',
      distance: '22.1 km'
    },
    {
      id: '21',
      title: 'Evening Jog & Social',
      sport: 'Running',
      date: '2025-10-20',
      time: '06:00 PM',
      location: 'Jakarta Barat',
      venue: 'Central Park Mall',
      price: 0,
      currentParticipants: 15,
      maxParticipants: 40,
      skillLevel: 'Beginner',
      hostName: 'Social Runners',
      hostAvatar: '🏃‍♀️',
      description: 'Easy jog followed by coffee',
      image: '🏃',
      distance: '7.6 km'
    },

    // Yoga Events
    {
      id: '22',
      title: 'Morning Yoga in the Park',
      sport: 'Yoga',
      date: '2025-10-20',
      time: '06:00 AM',
      location: 'Jakarta Selatan',
      venue: 'Taman Langsat',
      price: 0,
      currentParticipants: 8,
      maxParticipants: 15,
      skillLevel: 'Beginner',
      hostName: 'Rina Wellness',
      hostAvatar: '🧘',
      description: 'Free outdoor yoga session. Bring your own mat!',
      image: '🧘',
      distance: '1.2 km'
    },
    {
      id: '23',
      title: 'Power Yoga Class',
      sport: 'Yoga',
      date: '2025-10-22',
      time: '07:00 PM',
      location: 'Jakarta Selatan',
      venue: 'Senopati Yoga Studio',
      price: 120000,
      currentParticipants: 10,
      maxParticipants: 20,
      skillLevel: 'Intermediate',
      hostName: 'Yoga Master Nina',
      hostAvatar: '🧘‍♀️',
      description: 'Intense power yoga workout',
      image: '🧘',
      distance: '4.8 km'
    },
    {
      id: '24',
      title: 'Sunset Beach Yoga',
      sport: 'Yoga',
      date: '2025-10-24',
      time: '05:00 PM',
      location: 'Ancol',
      venue: 'Ancol Beach',
      price: 75000,
      currentParticipants: 12,
      maxParticipants: 25,
      skillLevel: 'Beginner',
      hostName: 'Beach Zen',
      hostAvatar: '🧘',
      description: 'Relaxing yoga with ocean view',
      image: '🧘',
      distance: '11.9 km'
    },
    {
      id: '25',
      title: 'Hot Yoga Session',
      sport: 'Yoga',
      date: '2025-10-25',
      time: '09:00 AM',
      location: 'Jakarta Pusat',
      venue: 'Grand Indonesia Wellness',
      price: 150000,
      currentParticipants: 14,
      maxParticipants: 15,
      skillLevel: 'Advanced',
      hostName: 'Hot Yoga Pro',
      hostAvatar: '🧘‍♂️',
      description: '90-minute hot yoga class',
      image: '🧘',
      distance: '5.3 km'
    },

    // Soccer/Football Events
    {
      id: '26',
      title: 'Futsal Friday Night',
      sport: 'Running',
      date: '2025-10-17',
      time: '08:00 PM',
      location: 'Jakarta Selatan',
      venue: 'Futsal Fatmawati',
      price: 50000,
      currentParticipants: 9,
      maxParticipants: 10,
      skillLevel: 'Intermediate',
      hostName: 'Futsal Heroes',
      hostAvatar: '⚽',
      description: '5v5 futsal match',
      image: '⚽',
      distance: '5.7 km'
    },
    {
      id: '27',
      title: 'Sunday Football League',
      sport: 'Running',
      date: '2025-10-27',
      time: '08:00 AM',
      location: 'Jakarta Timur',
      venue: 'Lapangan Rawamangun',
      price: 35000,
      currentParticipants: 18,
      maxParticipants: 22,
      skillLevel: 'Beginner',
      hostName: 'Weekend Warriors',
      hostAvatar: '⚽',
      description: 'Casual 11v11 football',
      image: '⚽',
      distance: '8.4 km'
    },
    {
      id: '28',
      title: 'Kids Futsal Training',
      sport: 'Running',
      date: '2025-10-21',
      time: '02:00 PM',
      location: 'Tangerang',
      venue: 'BSD Sports Arena',
      price: 75000,
      currentParticipants: 12,
      maxParticipants: 20,
      skillLevel: 'Beginner',
      hostName: 'Coach Fernando',
      hostAvatar: '⚽',
      description: 'Training for kids 8-12 years',
      image: '⚽',
      distance: '12.8 km'
    },

    // Cycling Events
    {
      id: '29',
      title: 'Weekend Cycling Tour',
      sport: 'Running',
      date: '2025-10-26',
      time: '06:00 AM',
      location: 'Bogor',
      venue: 'Kebun Raya Bogor',
      price: 50000,
      currentParticipants: 22,
      maxParticipants: 40,
      skillLevel: 'Beginner',
      hostName: 'Bike Squad',
      hostAvatar: '🚴',
      description: '30km leisure cycling',
      image: '🚴',
      distance: '16.3 km'
    },
    {
      id: '30',
      title: 'Mountain Bike Challenge',
      sport: 'Running',
      date: '2025-10-25',
      time: '07:00 AM',
      location: 'Sentul',
      venue: 'Sentul MTB Trail',
      price: 125000,
      currentParticipants: 15,
      maxParticipants: 25,
      skillLevel: 'Advanced',
      hostName: 'MTB Champions',
      hostAvatar: '🚵',
      description: 'Challenging mountain bike trail',
      image: '🚴',
      distance: '21.5 km'
    },
    {
      id: '31',
      title: 'City Night Ride',
      sport: 'Running',
      date: '2025-10-18',
      time: '08:00 PM',
      location: 'Jakarta Pusat',
      venue: 'Bundaran HI',
      price: 0,
      currentParticipants: 35,
      maxParticipants: 60,
      skillLevel: 'Beginner',
      hostName: 'Night Riders',
      hostAvatar: '🚴‍♂️',
      description: 'Free night cycling tour',
      image: '🚴',
      distance: '4.1 km'
    },

    // Swimming Events
    {
      id: '32',
      title: 'Early Morning Swim',
      sport: 'Running',
      date: '2025-10-20',
      time: '05:30 AM',
      location: 'Jakarta Selatan',
      venue: 'Senayan Aquatic Center',
      price: 40000,
      currentParticipants: 8,
      maxParticipants: 20,
      skillLevel: 'Intermediate',
      hostName: 'Swim Team',
      hostAvatar: '🏊',
      description: 'Open lane swimming session',
      image: '🏊',
      distance: '4.9 km'
    },
    {
      id: '33',
      title: 'Swimming Lesson for Adults',
      sport: 'Running',
      date: '2025-10-23',
      time: '06:00 PM',
      location: 'Jakarta Barat',
      venue: 'Puri Indah Pool',
      price: 100000,
      currentParticipants: 6,
      maxParticipants: 10,
      skillLevel: 'Beginner',
      hostName: 'Coach Michael',
      hostAvatar: '🏊‍♂️',
      description: 'Learn to swim basics',
      image: '🏊',
      distance: '9.2 km'
    },
    {
      id: '34',
      title: 'Triathlon Training Swim',
      sport: 'Running',
      date: '2025-10-24',
      time: '06:00 AM',
      location: 'Jakarta Utara',
      venue: 'Kelapa Gading Pool',
      price: 65000,
      currentParticipants: 12,
      maxParticipants: 15,
      skillLevel: 'Advanced',
      hostName: 'Tri-Athletes',
      hostAvatar: '🏊',
      description: 'Intensive swim training',
      image: '🏊',
      distance: '10.7 km'
    },

    // Boxing/Martial Arts
    {
      id: '35',
      title: 'Boxing Fitness Class',
      sport: 'Running',
      date: '2025-10-22',
      time: '06:30 PM',
      location: 'Jakarta Selatan',
      venue: 'Fight Club Gym',
      price: 85000,
      currentParticipants: 11,
      maxParticipants: 15,
      skillLevel: 'Intermediate',
      hostName: 'Coach Rocky',
      hostAvatar: '🥊',
      description: 'High intensity boxing workout',
      image: '🥊',
      distance: '6.1 km'
    },
    {
      id: '36',
      title: 'Muay Thai Fundamentals',
      sport: 'Running',
      date: '2025-10-19',
      time: '07:00 PM',
      location: 'Jakarta Pusat',
      venue: 'Tiger Muay Thai Jakarta',
      price: 120000,
      currentParticipants: 8,
      maxParticipants: 12,
      skillLevel: 'Beginner',
      hostName: 'Master Somchai',
      hostAvatar: '🥋',
      description: 'Introduction to Muay Thai',
      image: '🥊',
      distance: '5.5 km'
    },
    {
      id: '37',
      title: 'Kickboxing Sparring',
      sport: 'Running',
      date: '2025-10-27',
      time: '05:00 PM',
      location: 'Bekasi',
      venue: 'Champions Gym',
      price: 75000,
      currentParticipants: 9,
      maxParticipants: 10,
      skillLevel: 'Advanced',
      hostName: 'Fight Master',
      hostAvatar: '🥊',
      description: 'Advanced sparring session',
      image: '🥊',
      distance: '15.2 km'
    },

    // Additional Badminton
    {
      id: '38',
      title: 'Lunch Break Badminton',
      sport: 'Badminton',
      date: '2025-10-21',
      time: '12:00 PM',
      location: 'Jakarta Pusat',
      venue: 'Kuningan City Sports',
      price: 60000,
      currentParticipants: 6,
      maxParticipants: 8,
      skillLevel: 'Intermediate',
      hostName: 'Office Warriors',
      hostAvatar: '💼',
      description: 'Quick badminton during lunch',
      image: '🏸',
      distance: '3.8 km'
    },
    {
      id: '39',
      title: 'Mixed Doubles Tournament',
      sport: 'Badminton',
      date: '2025-10-28',
      time: '02:00 PM',
      location: 'Depok',
      venue: 'Margonda Sports Hall',
      price: 90000,
      currentParticipants: 14,
      maxParticipants: 16,
      skillLevel: 'Advanced',
      hostName: 'Tournament Organizer',
      hostAvatar: '🏆',
      description: 'Competitive mixed doubles',
      image: '🏸',
      distance: '12.4 km'
    },

    // More Basketball
    {
      id: '40',
      title: 'Youth Basketball Camp',
      sport: 'Basketball',
      date: '2025-10-26',
      time: '09:00 AM',
      location: 'Jakarta Selatan',
      venue: 'Senayan Basketball Hall',
      price: 150000,
      currentParticipants: 24,
      maxParticipants: 30,
      skillLevel: 'Beginner',
      hostName: 'Basketball Academy',
      hostAvatar: '🏫',
      description: 'Training camp for youth 10-16',
      image: '🏀',
      distance: '5.2 km'
    },
    {
      id: '41',
      title: 'Women\'s Basketball League',
      sport: 'Basketball',
      date: '2025-10-24',
      time: '07:00 PM',
      location: 'Tangerang',
      venue: 'Living World Court',
      price: 45000,
      currentParticipants: 8,
      maxParticipants: 10,
      skillLevel: 'Intermediate',
      hostName: 'Lady Ballers',
      hostAvatar: '👩‍🦰',
      description: 'Women\'s basketball matches',
      image: '🏀',
      distance: '13.1 km'
    },

    // Table Tennis
    {
      id: '42',
      title: 'Table Tennis Tournament',
      sport: 'Tennis',
      date: '2025-10-23',
      time: '06:00 PM',
      location: 'Jakarta Timur',
      venue: 'Cibubur TT Center',
      price: 40000,
      currentParticipants: 15,
      maxParticipants: 20,
      skillLevel: 'Intermediate',
      hostName: 'Ping Pong Masters',
      hostAvatar: '🏓',
      description: 'Singles table tennis tournament',
      image: '🏓',
      distance: '11.6 km'
    },
    {
      id: '43',
      title: 'Beginner Table Tennis Class',
      sport: 'Tennis',
      date: '2025-10-21',
      time: '10:00 AM',
      location: 'Jakarta Barat',
      venue: 'Tomang TT Club',
      price: 55000,
      currentParticipants: 7,
      maxParticipants: 12,
      skillLevel: 'Beginner',
      hostName: 'Coach Lee',
      hostAvatar: '🏓',
      description: 'Learn table tennis basics',
      image: '🏓',
      distance: '8.3 km'
    },

    // Golf
    {
      id: '44',
      title: 'Weekend Golf Round',
      sport: 'Running',
      date: '2025-10-26',
      time: '07:00 AM',
      location: 'Tangerang',
      venue: 'Damai Indah Golf',
      price: 350000,
      currentParticipants: 3,
      maxParticipants: 4,
      skillLevel: 'Intermediate',
      hostName: 'Golf Buddies',
      hostAvatar: '⛳',
      description: '18 holes golf round',
      image: '⛳',
      distance: '16.8 km'
    },
    {
      id: '45',
      title: 'Golf Clinic for Beginners',
      sport: 'Running',
      date: '2025-10-24',
      time: '08:00 AM',
      location: 'Jakarta Selatan',
      venue: 'Senayan Golf Driving Range',
      price: 200000,
      currentParticipants: 8,
      maxParticipants: 15,
      skillLevel: 'Beginner',
      hostName: 'Pro Golfer',
      hostAvatar: '⛳',
      description: 'Introduction to golf',
      image: '⛳',
      distance: '4.5 km'
    },

    // Rock Climbing
    {
      id: '46',
      title: 'Indoor Rock Climbing',
      sport: 'Hiking',
      date: '2025-10-22',
      time: '06:00 PM',
      location: 'Jakarta Selatan',
      venue: 'Boulder House',
      price: 85000,
      currentParticipants: 6,
      maxParticipants: 12,
      skillLevel: 'Beginner',
      hostName: 'Climb Masters',
      hostAvatar: '🧗',
      description: 'Beginner-friendly climbing',
      image: '🧗',
      distance: '7.2 km'
    },
    {
      id: '47',
      title: 'Advanced Bouldering Session',
      sport: 'Hiking',
      date: '2025-10-25',
      time: '07:00 PM',
      location: 'Jakarta Pusat',
      venue: 'Climb Central',
      price: 100000,
      currentParticipants: 9,
      maxParticipants: 10,
      skillLevel: 'Advanced',
      hostName: 'Boulder Bros',
      hostAvatar: '🧗‍♂️',
      description: 'Challenging boulder problems',
      image: '🧗',
      distance: '6.9 km'
    },

    // More Yoga
    {
      id: '48',
      title: 'Aerial Yoga Class',
      sport: 'Yoga',
      date: '2025-10-27',
      time: '10:00 AM',
      location: 'Jakarta Selatan',
      venue: 'Fly Yoga Studio',
      price: 175000,
      currentParticipants: 7,
      maxParticipants: 10,
      skillLevel: 'Intermediate',
      hostName: 'Aerial Instructor',
      hostAvatar: '🎪',
      description: 'Yoga with hammocks',
      image: '🧘',
      distance: '5.8 km'
    },
    {
      id: '49',
      title: 'Meditation & Yoga Retreat',
      sport: 'Yoga',
      date: '2025-10-28',
      time: '08:00 AM',
      location: 'Bogor',
      venue: 'Puncak Retreat Center',
      price: 250000,
      currentParticipants: 12,
      maxParticipants: 20,
      skillLevel: 'Beginner',
      hostName: 'Zen Master',
      hostAvatar: '🧘‍♂️',
      description: 'Full day yoga and meditation',
      image: '🧘',
      distance: '19.3 km'
    },

    // Dance Fitness
    {
      id: '50',
      title: 'Zumba Dance Party',
      sport: 'Running',
      date: '2025-10-23',
      time: '07:00 PM',
      location: 'Jakarta Barat',
      venue: 'Central Park Dance Studio',
      price: 60000,
      currentParticipants: 18,
      maxParticipants: 25,
      skillLevel: 'Beginner',
      hostName: 'Dance Instructor Maria',
      hostAvatar: '💃',
      description: 'High energy dance workout',
      image: '💃',
      distance: '7.9 km'
    },
    {
      id: '51',
      title: 'Hip Hop Dance Class',
      sport: 'Running',
      date: '2025-10-24',
      time: '08:00 PM',
      location: 'Jakarta Pusat',
      venue: 'Urban Dance Studio',
      price: 80000,
      currentParticipants: 14,
      maxParticipants: 20,
      skillLevel: 'Intermediate',
      hostName: 'B-Boy Danny',
      hostAvatar: '🕺',
      description: 'Learn hip hop choreography',
      image: '💃',
      distance: '5.1 km'
    },

    // CrossFit / HIIT
    {
      id: '52',
      title: 'CrossFit Bootcamp',
      sport: 'Running',
      date: '2025-10-20',
      time: '06:00 AM',
      location: 'Jakarta Selatan',
      venue: 'CrossFit Jakarta',
      price: 100000,
      currentParticipants: 15,
      maxParticipants: 20,
      skillLevel: 'Advanced',
      hostName: 'Coach Alex',
      hostAvatar: '💪',
      description: 'Intense CrossFit WOD',
      image: '💪',
      distance: '6.3 km'
    },
    {
      id: '53',
      title: 'HIIT Training Session',
      sport: 'Running',
      date: '2025-10-22',
      time: '06:30 PM',
      location: 'Tangerang',
      venue: 'Fitness First BSD',
      price: 75000,
      currentParticipants: 12,
      maxParticipants: 18,
      skillLevel: 'Intermediate',
      hostName: 'Trainer Sarah',
      hostAvatar: '🏋️',
      description: '45-min high intensity workout',
      image: '💪',
      distance: '11.8 km'
    }
  ];

  private sportTypes: SportType[] = [
    { name: 'All', icon: '🎯' },
    { name: 'Badminton', icon: '🏸' },
    { name: 'Hiking', icon: '🥾' },
    { name: 'Padel', icon: '🎾' },
    { name: 'Basketball', icon: '🏀' },
    { name: 'Volleyball', icon: '🏐' },
    { name: 'Tennis', icon: '🎾' },
    { name: 'Running', icon: '🏃' },
    { name: 'Yoga', icon: '🧘' }
  ];

  getEvents(): Event[] {
    return this.mockEvents;
  }

  getSportTypes(): SportType[] {
    return this.sportTypes;
  }

  getEventById(id: string): Event | undefined {
    return this.mockEvents.find(event => event.id === id);
  }
}

